/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateOrderStatusDto
 */
export interface UpdateOrderStatusDto {
    /**
     * New order status ID
     * @type {number}
     * @memberof UpdateOrderStatusDto
     */
    'status_id': UpdateOrderStatusDtoStatusIdEnum;
    /**
     * Note about status change (optional)
     * @type {string}
     * @memberof UpdateOrderStatusDto
     */
    'note'?: string;
}

export const UpdateOrderStatusDtoStatusIdEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7
} as const;

export type UpdateOrderStatusDtoStatusIdEnum = typeof UpdateOrderStatusDtoStatusIdEnum[keyof typeof UpdateOrderStatusDtoStatusIdEnum];


