/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MomoControllerHandleIPNRequest
 */
export interface MomoControllerHandleIPNRequest {
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'partnerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'orderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'requestId'?: string;
    /**
     * 
     * @type {number}
     * @memberof MomoControllerHandleIPNRequest
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'orderInfo'?: string;
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'orderType'?: string;
    /**
     * 
     * @type {number}
     * @memberof MomoControllerHandleIPNRequest
     */
    'transId'?: number;
    /**
     * 
     * @type {number}
     * @memberof MomoControllerHandleIPNRequest
     */
    'resultCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'payType'?: string;
    /**
     * 
     * @type {number}
     * @memberof MomoControllerHandleIPNRequest
     */
    'responseTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'extraData'?: string;
    /**
     * 
     * @type {string}
     * @memberof MomoControllerHandleIPNRequest
     */
    'signature'?: string;
}

