/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { MomoControllerHandleIPNRequest } from '../models';
/**
 * PaymentsMoMoApi - axios parameter creator
 * @export
 */
export const PaymentsMoMoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get human-readable description for MoMo result code
         * @summary Get MoMo Result Code Description
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        momoControllerGetResultCodeDescription: async (code: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('momoControllerGetResultCodeDescription', 'code', code)
            const localVarPath = `/api/v1/payments/momo/result-codes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Receive payment notification from MoMo. This endpoint is called by MoMo server, not by client.
         * @summary MoMo IPN Callback
         * @param {MomoControllerHandleIPNRequest} momoControllerHandleIPNRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        momoControllerHandleIPN: async (momoControllerHandleIPNRequest: MomoControllerHandleIPNRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'momoControllerHandleIPNRequest' is not null or undefined
            assertParamExists('momoControllerHandleIPN', 'momoControllerHandleIPNRequest', momoControllerHandleIPNRequest)
            const localVarPath = `/api/v1/payments/momo/ipn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(momoControllerHandleIPNRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Handle redirect from MoMo after payment. Redirects user to frontend with payment result.
         * @summary MoMo Return URL
         * @param {string} orderId 
         * @param {string} resultCode 
         * @param {string} message 
         * @param {string} transId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        momoControllerHandleReturn: async (orderId: string, resultCode: string, message: string, transId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('momoControllerHandleReturn', 'orderId', orderId)
            // verify required parameter 'resultCode' is not null or undefined
            assertParamExists('momoControllerHandleReturn', 'resultCode', resultCode)
            // verify required parameter 'message' is not null or undefined
            assertParamExists('momoControllerHandleReturn', 'message', message)
            // verify required parameter 'transId' is not null or undefined
            assertParamExists('momoControllerHandleReturn', 'transId', transId)
            const localVarPath = `/api/v1/payments/momo/return`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (orderId !== undefined) {
                localVarQueryParameter['orderId'] = orderId;
            }

            if (resultCode !== undefined) {
                localVarQueryParameter['resultCode'] = resultCode;
            }

            if (message !== undefined) {
                localVarQueryParameter['message'] = message;
            }

            if (transId !== undefined) {
                localVarQueryParameter['transId'] = transId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Query the status of a MoMo transaction
         * @summary Query MoMo Transaction
         * @param {string} orderId 
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        momoControllerQueryTransaction: async (orderId: string, requestId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('momoControllerQueryTransaction', 'orderId', orderId)
            // verify required parameter 'requestId' is not null or undefined
            assertParamExists('momoControllerQueryTransaction', 'requestId', requestId)
            const localVarPath = `/api/v1/payments/momo/query`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (orderId !== undefined) {
                localVarQueryParameter['orderId'] = orderId;
            }

            if (requestId !== undefined) {
                localVarQueryParameter['requestId'] = requestId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentsMoMoApi - functional programming interface
 * @export
 */
export const PaymentsMoMoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentsMoMoApiAxiosParamCreator(configuration)
    return {
        /**
         * Get human-readable description for MoMo result code
         * @summary Get MoMo Result Code Description
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async momoControllerGetResultCodeDescription(code: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.momoControllerGetResultCodeDescription(code, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PaymentsMoMoApi.momoControllerGetResultCodeDescription']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Receive payment notification from MoMo. This endpoint is called by MoMo server, not by client.
         * @summary MoMo IPN Callback
         * @param {MomoControllerHandleIPNRequest} momoControllerHandleIPNRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async momoControllerHandleIPN(momoControllerHandleIPNRequest: MomoControllerHandleIPNRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.momoControllerHandleIPN(momoControllerHandleIPNRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PaymentsMoMoApi.momoControllerHandleIPN']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Handle redirect from MoMo after payment. Redirects user to frontend with payment result.
         * @summary MoMo Return URL
         * @param {string} orderId 
         * @param {string} resultCode 
         * @param {string} message 
         * @param {string} transId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async momoControllerHandleReturn(orderId: string, resultCode: string, message: string, transId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.momoControllerHandleReturn(orderId, resultCode, message, transId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PaymentsMoMoApi.momoControllerHandleReturn']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Query the status of a MoMo transaction
         * @summary Query MoMo Transaction
         * @param {string} orderId 
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async momoControllerQueryTransaction(orderId: string, requestId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.momoControllerQueryTransaction(orderId, requestId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PaymentsMoMoApi.momoControllerQueryTransaction']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * PaymentsMoMoApi - factory interface
 * @export
 */
export const PaymentsMoMoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentsMoMoApiFp(configuration)
    return {
        /**
         * Get human-readable description for MoMo result code
         * @summary Get MoMo Result Code Description
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        momoControllerGetResultCodeDescription(code: string, options?: any): AxiosPromise<void> {
            return localVarFp.momoControllerGetResultCodeDescription(code, options).then((request) => request(axios, basePath));
        },
        /**
         * Receive payment notification from MoMo. This endpoint is called by MoMo server, not by client.
         * @summary MoMo IPN Callback
         * @param {MomoControllerHandleIPNRequest} momoControllerHandleIPNRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        momoControllerHandleIPN(momoControllerHandleIPNRequest: MomoControllerHandleIPNRequest, options?: any): AxiosPromise<void> {
            return localVarFp.momoControllerHandleIPN(momoControllerHandleIPNRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Handle redirect from MoMo after payment. Redirects user to frontend with payment result.
         * @summary MoMo Return URL
         * @param {string} orderId 
         * @param {string} resultCode 
         * @param {string} message 
         * @param {string} transId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        momoControllerHandleReturn(orderId: string, resultCode: string, message: string, transId: string, options?: any): AxiosPromise<void> {
            return localVarFp.momoControllerHandleReturn(orderId, resultCode, message, transId, options).then((request) => request(axios, basePath));
        },
        /**
         * Query the status of a MoMo transaction
         * @summary Query MoMo Transaction
         * @param {string} orderId 
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        momoControllerQueryTransaction(orderId: string, requestId: string, options?: any): AxiosPromise<void> {
            return localVarFp.momoControllerQueryTransaction(orderId, requestId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaymentsMoMoApi - interface
 * @export
 * @interface PaymentsMoMoApi
 */
export interface PaymentsMoMoApiInterface {
    /**
     * Get human-readable description for MoMo result code
     * @summary Get MoMo Result Code Description
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsMoMoApiInterface
     */
    momoControllerGetResultCodeDescription(code: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Receive payment notification from MoMo. This endpoint is called by MoMo server, not by client.
     * @summary MoMo IPN Callback
     * @param {MomoControllerHandleIPNRequest} momoControllerHandleIPNRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsMoMoApiInterface
     */
    momoControllerHandleIPN(momoControllerHandleIPNRequest: MomoControllerHandleIPNRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Handle redirect from MoMo after payment. Redirects user to frontend with payment result.
     * @summary MoMo Return URL
     * @param {string} orderId 
     * @param {string} resultCode 
     * @param {string} message 
     * @param {string} transId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsMoMoApiInterface
     */
    momoControllerHandleReturn(orderId: string, resultCode: string, message: string, transId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Query the status of a MoMo transaction
     * @summary Query MoMo Transaction
     * @param {string} orderId 
     * @param {string} requestId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsMoMoApiInterface
     */
    momoControllerQueryTransaction(orderId: string, requestId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * PaymentsMoMoApi - object-oriented interface
 * @export
 * @class PaymentsMoMoApi
 * @extends {BaseAPI}
 */
export class PaymentsMoMoApi extends BaseAPI implements PaymentsMoMoApiInterface {
    /**
     * Get human-readable description for MoMo result code
     * @summary Get MoMo Result Code Description
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsMoMoApi
     */
    public momoControllerGetResultCodeDescription(code: string, options?: RawAxiosRequestConfig) {
        return PaymentsMoMoApiFp(this.configuration).momoControllerGetResultCodeDescription(code, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Receive payment notification from MoMo. This endpoint is called by MoMo server, not by client.
     * @summary MoMo IPN Callback
     * @param {MomoControllerHandleIPNRequest} momoControllerHandleIPNRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsMoMoApi
     */
    public momoControllerHandleIPN(momoControllerHandleIPNRequest: MomoControllerHandleIPNRequest, options?: RawAxiosRequestConfig) {
        return PaymentsMoMoApiFp(this.configuration).momoControllerHandleIPN(momoControllerHandleIPNRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Handle redirect from MoMo after payment. Redirects user to frontend with payment result.
     * @summary MoMo Return URL
     * @param {string} orderId 
     * @param {string} resultCode 
     * @param {string} message 
     * @param {string} transId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsMoMoApi
     */
    public momoControllerHandleReturn(orderId: string, resultCode: string, message: string, transId: string, options?: RawAxiosRequestConfig) {
        return PaymentsMoMoApiFp(this.configuration).momoControllerHandleReturn(orderId, resultCode, message, transId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Query the status of a MoMo transaction
     * @summary Query MoMo Transaction
     * @param {string} orderId 
     * @param {string} requestId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsMoMoApi
     */
    public momoControllerQueryTransaction(orderId: string, requestId: string, options?: RawAxiosRequestConfig) {
        return PaymentsMoMoApiFp(this.configuration).momoControllerQueryTransaction(orderId, requestId, options).then((request) => request(this.axios, this.basePath));
    }
}

